version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  prisma:
    image: prismagraphql/prisma:1.34.10
    depends_on:
      - db
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: db
            database: mydatabase
            user: root
            password: rootpassword
volumes:
  mysql_data:
